#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          microsoft:
#            authorization-uri: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/organizations/oauth2/v2.0/token
#            jwk-set-uri: https://login.microsoftonline.com/organizations/discovery/v2.0/keys
#        registration:
#          microsoft:
#            provider: azure-ad
#            client-id: ${CLIENT_ID}
#            client-secret: ${CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
#            scope: openid,profile
#server:
#  forward-headers-strategy: native
spring:
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: User.Read
            client-name: Microsoft
            client-alias: microsoft
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/authorize?resource=https://graph.microsoft.com/
            token-uri: https://login.microsoftonline.com/common/oauth2/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            user-name-attribute: id
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/keys